import { useState } from "react";
import {
  ArrowDownLeft, ArrowUpRight, BarChart3, Check, ChevronRight, CircleDollarSign,
  Compass, Download, FileText, LayoutDashboard, LogOut, MapPinned, Menu, Mountain, Plus, Search, Settings,
  Trash2, Users, Wallet, X,
} from "lucide-react";
import type { AppData, Expense, ExpenseCategory, Income, PaymentMethod } from "./types";
import { addExpense, addIncome, addMember, addPerson, loadData, removeExpense, removeIncome } from "./lib/store";
import { formatDate, formatRs } from "./lib/utils";
import { downloadReportPdf } from "./lib/pdf";
import { signOut } from "./lib/repository";

type Page = "Dashboard" | "Income" | "Expenses" | "Members" | "Reports";
const methods: PaymentMethod[] = ["Cash", "Bank Transfer", "Easypaisa", "JazzCash", "Other Online"];
const categories: ExpenseCategory[] = ["Vehicle", "Fuel", "Accommodation", "Food", "Toll / Tax", "Other"];

function StatCard({ label, value, icon, tone = "neutral", detail }: { label: string; value: string; icon: React.ReactNode; tone?: string; detail?: string }) {
  return <div className={`stat-card ${tone}`}><div className="stat-icon">{icon}</div><div><p className="eyebrow">{label}</p><strong>{value}</strong>{detail && <small>{detail}</small>}</div></div>;
}

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={(e) => e.stopPropagation()}><header><div><p className="eyebrow">Quick entry</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={20} /></button></header>{children}</section></div>;
}

export function App() {
  const [data, setData] = useState<AppData>(loadData);
  const [page, setPage] = useState<Page>("Dashboard");
  const [modal, setModal] = useState<"income" | "expense" | "member" | null>(null);
  const [query, setQuery] = useState("");

  const refresh = (next: AppData) => setData(next);
  const totalIncome = data.incomes.reduce((sum, item) => sum + item.amount, 0);
  const totalExpenses = data.expenses.reduce((sum, item) => sum + item.amount, 0);
  const balance = totalIncome - totalExpenses;
  const people = Object.fromEntries(data.people.map((person) => [person.id, person.name]));
  const members = Object.fromEntries(data.members.map((member) => [member.id, member]));
  const memberPaid = (memberId: string) => data.incomes.filter((item) => item.memberId === memberId).reduce((sum, item) => sum + item.amount, 0);
  const recent = [...data.expenses.map((item) => ({ ...item, kind: "expense" as const })), ...data.incomes.map((item) => ({ ...item, kind: "income" as const }))].sort((a, b) => `${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)).slice(0, 6);

  const filteredExpenses = data.expenses.filter((item) => `${item.description} ${item.location} ${item.category} ${people[item.paidByPersonId]}`.toLowerCase().includes(query.toLowerCase()));
  const categoriesTotal = categories.map((category) => ({ category, amount: data.expenses.filter((item) => item.category === category).reduce((sum, item) => sum + item.amount, 0) })).filter((item) => item.amount > 0);
  const cashIncome = data.incomes.filter((item) => item.paymentMethod === "Cash").reduce((sum, item) => sum + item.amount, 0);
  const cashExpenses = data.expenses.filter((item) => item.paymentMethod === "Cash").reduce((sum, item) => sum + item.amount, 0);

  function handleDelete(kind: "income" | "expense", id: string) {
    if (!window.confirm(`Delete this ${kind} record? This cannot be undone.`)) return;
    refresh(kind === "income" ? removeIncome(data, id) : removeExpense(data, id));
  }

  async function handleLogout() {
    await signOut();
  }

  function exportCsv() {
    const rows = [["Type", "Amount", "Category/Member", "Person", "Method", "Location", "Date", "Time"], ...data.expenses.map((e) => ["Expense", String(e.amount), e.category, people[e.paidByPersonId], e.paymentMethod, e.location, e.date, e.time]), ...data.incomes.map((i) => ["Income", String(i.amount), people[members[i.memberId]?.personId], people[i.receivedByPersonId], i.paymentMethod, "", i.date, i.time])];
    const blob = new Blob([rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\n")], { type: "text/csv" });
    const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "kumrat-tour-transactions.csv"; link.click(); URL.revokeObjectURL(url);
  }

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><Mountain size={19} /></div><div><strong>Kumrat</strong><span>Tour Finance</span></div></div>
      <div className="tour-mini"><span className="status-dot" /> Live tour<div className="tour-name">{data.tour.name}</div><small>{data.tour.origin} → {data.tour.destination}</small></div>
      <nav>{([["Dashboard", LayoutDashboard], ["Income", ArrowDownLeft], ["Expenses", ArrowUpRight], ["Members", Users], ["Reports", BarChart3]] as const).map(([label, Icon]) => <button key={label} className={page === label ? "nav-item active" : "nav-item"} onClick={() => setPage(label)}><Icon size={18} />{label}</button>)}</nav>
      <div className="sidebar-bottom"><button className="nav-item"><Settings size={18} />Settings</button><button className="nav-item logout-item" onClick={handleLogout}><LogOut size={18} />Log out</button><small>17–18 September 2026</small></div>
    </aside>
    <main className="main">
      <header className="topbar"><button className="mobile-menu icon-button" aria-label="Menu"><Menu size={21} /></button><div><p className="eyebrow">Thursday, 17 September 2026</p><h1>{page}</h1></div><div className="top-actions"><label className="search"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search transactions..." /></label><button className="avatar">A</button></div></header>
      {page === "Dashboard" && <Dashboard data={data} totalIncome={totalIncome} totalExpenses={totalExpenses} balance={balance} cashIncome={cashIncome} cashExpenses={cashExpenses} categoriesTotal={categoriesTotal} recent={recent} people={people} members={members} memberPaid={memberPaid} onAdd={(kind) => setModal(kind)} />}
      {page === "Income" && <TransactionPage title="Income" subtitle="Member contributions and money received" type="income" data={data} people={people} members={members} query={query} onAdd={() => setModal("income")} onDelete={handleDelete} />}
      {page === "Expenses" && <TransactionPage title="Expenses" subtitle="Every rupee spent, traceable" type="expense" data={data} people={people} members={members} query={query} onAdd={() => setModal("expense")} onDelete={handleDelete} />}
      {page === "Members" && <MembersPage data={data} people={people} memberPaid={memberPaid} onAdd={() => setModal("member")} />}
      {page === "Reports" && <Reports data={data} people={people} members={members} totalIncome={totalIncome} totalExpenses={totalExpenses} balance={balance} categoriesTotal={categoriesTotal} exportCsv={exportCsv} exportPdf={(mode) => downloadReportPdf(data, mode)} />}
    </main>
    {modal === "income" && <IncomeForm data={data} people={people} members={members} onClose={() => setModal(null)} onSaved={(next) => { refresh(next); setModal(null); }} />}
    {modal === "expense" && <ExpenseForm data={data} people={people} onClose={() => setModal(null)} onSaved={(next) => { refresh(next); setModal(null); }} />}
    {modal === "member" && <MemberForm data={data} onClose={() => setModal(null)} onSaved={(next) => { refresh(next); setModal(null); }} />}
    <div className="fab-wrap"><button className="fab" onClick={() => setModal("expense")}><Plus size={22} />Add transaction</button></div>
  </div>;
}

function Dashboard({ data, totalIncome, totalExpenses, balance, cashIncome, cashExpenses, categoriesTotal, recent, people, members, memberPaid, onAdd }: { data: AppData; totalIncome: number; totalExpenses: number; balance: number; cashIncome: number; cashExpenses: number; categoriesTotal: { category: ExpenseCategory; amount: number }[]; recent: Array<(Income | Expense) & { kind: "income" | "expense" }>; people: Record<string, string>; members: Record<string, AppData["members"][number]>; memberPaid: (id: string) => number; onAdd: (kind: "income" | "expense") => void }) {
  return <div className="content">
    <section className="hero"><div><p className="eyebrow light"><Compass size={12} /> Your journey, accounted for</p><h2>{data.tour.name}</h2><p><MapPinned size={14} /> {data.tour.origin} <span>→</span> {data.tour.destination} <span>→</span> {data.tour.origin}</p><div className="date-pill">17–18 Sep 2026</div></div><div className="mountain-scene" aria-label="Kumrat mountain route illustration"><div className="moon" /><div className="ridge ridge-back" /><div className="ridge ridge-front" /><div className="scene-balance"><CircleDollarSign size={17} /><span>Live balance</span><strong>{formatRs(balance)}</strong></div></div></section>
    <div className="quick-actions"><button onClick={() => onAdd("income")}><ArrowDownLeft size={18} />Add income</button><button onClick={() => onAdd("expense")}><ArrowUpRight size={18} />Add expense</button><button className="ghost" onClick={() => window.print()}><FileText size={18} />View summary</button></div>
    <section className="stats-grid"><StatCard label="Total collected" value={formatRs(totalIncome)} icon={<ArrowDownLeft size={19} />} tone="positive" detail={`${data.incomes.length} payments recorded`} /><StatCard label="Total expenses" value={formatRs(totalExpenses)} icon={<ArrowUpRight size={19} />} tone="negative" detail={`${data.expenses.length} expenses recorded`} /><StatCard label="Remaining balance" value={formatRs(balance)} icon={<Wallet size={19} />} tone="balance" detail="Income minus expenses" /><StatCard label="Members paid" value={`${data.members.filter((m) => memberPaid(m.id) >= m.expectedContribution).length} / ${data.members.length}`} icon={<Users size={19} />} detail="Fully paid contributions" /></section>
    <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Money flow</p><h3>Cash vs online</h3></div><span className="muted">All time</span></div><div className="flow-row"><div><span className="flow-dot cash" /><p>Cash</p><strong>{formatRs(cashIncome - cashExpenses)}</strong><small>Collected {formatRs(cashIncome)} · Spent {formatRs(cashExpenses)}</small></div><div><span className="flow-dot online" /><p>Online</p><strong>{formatRs((totalIncome - cashIncome) - (totalExpenses - cashExpenses))}</strong><small>Collected {formatRs(totalIncome - cashIncome)} · Spent {formatRs(totalExpenses - cashExpenses)}</small></div></div><div className="progress"><span style={{ width: `${totalIncome ? Math.min(100, (totalExpenses / totalIncome) * 100) : 0}%` }} /></div><small className="muted">Expense utilization · {totalIncome ? Math.round((totalExpenses / totalIncome) * 100) : 0}% of collected funds</small></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Where it went</p><h3>Expense breakdown</h3></div><BarChart3 size={19} className="muted" /></div>{categoriesTotal.length ? categoriesTotal.map((item) => <div className="category-row" key={item.category}><div><span className={`category-dot ${item.category.toLowerCase().replaceAll(" ", "-")}`} /><span>{item.category}</span></div><strong>{formatRs(item.amount)}</strong></div>) : <EmptyState text="No expenses yet" />}</section></div>
    <section className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">Latest movements</p><h3>Recent activity</h3></div><ChevronRight size={19} className="muted" /></div>{recent.length ? recent.map((item) => { const isIncome = item.kind === "income"; const income = item as Income; const expense = item as Expense; return <div className="activity-row" key={item.id}><div className={`activity-icon ${isIncome ? "income" : "expense"}`}>{isIncome ? <ArrowDownLeft size={17} /> : <ArrowUpRight size={17} />}</div><div className="activity-main"><strong>{isIncome ? people[members[income.memberId]?.personId] : expense.description}</strong><span>{isIncome ? `Received by ${people[income.receivedByPersonId]}` : `${people[expense.paidByPersonId]} · ${expense.location}`}</span></div><div className="activity-meta"><strong className={isIncome ? "positive-text" : ""}>{isIncome ? "+" : "-"}{formatRs(item.amount)}</strong><span>{formatDate(item.date)} · {item.time}</span></div></div> }) : <EmptyState text="Your tour activity will appear here" />}</section>
  </div>;
}

function EmptyState({ text }: { text: string }) { return <div className="empty"><CircleDollarSign size={22} /><span>{text}</span></div>; }

function TransactionPage({ title, subtitle, type, data, people, members, query, onAdd, onDelete }: { title: string; subtitle: string; type: "income" | "expense"; data: AppData; people: Record<string, string>; members: Record<string, AppData["members"][number]>; query: string; onAdd: () => void; onDelete: (type: "income" | "expense", id: string) => void }) {
  const isIncome = type === "income";
  const rows = isIncome ? data.incomes.filter((item) => `${people[members[item.memberId]?.personId]} ${people[item.receivedByPersonId]} ${item.paymentMethod}`.toLowerCase().includes(query.toLowerCase())) : data.expenses.filter((item) => `${item.description} ${item.location} ${item.category} ${people[item.paidByPersonId]}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="content"><div className="page-intro"><div><p className="eyebrow">Transaction ledger</p><h2>{title}</h2><p>{subtitle}</p></div><button className="primary-button" onClick={onAdd}><Plus size={18} /> Add {isIncome ? "income" : "expense"}</button></div><div className="filter-strip"><button className="filter active">All</button><button className="filter">Cash</button><button className="filter">Online</button><span className="filter-spacer" /><span className="muted">{rows.length} records</span></div><section className="panel list-panel">{rows.length ? rows.map((item) => isIncome ? <div className="ledger-row" key={item.id}><div className="activity-icon income"><ArrowDownLeft size={17} /></div><div className="activity-main"><strong>{people[members[(item as Income).memberId]?.personId]}</strong><span>Received by {people[(item as Income).receivedByPersonId]} · {(item as Income).paymentMethod}</span></div><div className="activity-meta"><strong className="positive-text">+{formatRs(item.amount)}</strong><span>{formatDate(item.date)} · {item.time}</span></div><button className="delete-button" onClick={() => onDelete("income", item.id)} aria-label="Delete income"><Trash2 size={16} /></button></div> : <div className="ledger-row" key={item.id}><div className="activity-icon expense"><ArrowUpRight size={17} /></div><div className="activity-main"><strong>{(item as Expense).description}</strong><span>{(item as Expense).category} · {people[(item as Expense).paidByPersonId]} · {(item as Expense).location}</span></div><div className="activity-meta"><strong>-{formatRs(item.amount)}</strong><span>{formatDate(item.date)} · {item.time}</span></div><button className="delete-button" onClick={() => onDelete("expense", item.id)} aria-label="Delete expense"><Trash2 size={16} /></button></div>) : <EmptyState text={`No ${title.toLowerCase()} match your search`} />}</section></div>;
}

function MembersPage({ data, people, memberPaid, onAdd }: { data: AppData; people: Record<string, string>; memberPaid: (id: string) => number; onAdd: () => void }) {
  return <div className="content"><div className="page-intro"><div><p className="eyebrow">People & contributions</p><h2>Members</h2><p>Expected contribution and payment status at a glance.</p></div><button className="primary-button" onClick={onAdd}><Plus size={18} /> Add member</button></div><section className="member-grid">{data.members.map((member) => { const paid = memberPaid(member.id); const status = paid === 0 ? "Pending" : paid < member.expectedContribution ? "Partial" : "Paid"; return <article className="member-card" key={member.id}><div className="member-top"><div className="avatar large">{people[member.personId]?.[0]}</div><div><h3>{people[member.personId]}</h3><span className={`status ${status.toLowerCase()}`}>{status}</span></div><ChevronRight size={18} className="muted" /></div><div className="member-values"><div><small>Paid</small><strong>{formatRs(paid)}</strong></div><div><small>Expected</small><strong>{formatRs(member.expectedContribution)}</strong></div><div><small>Remaining</small><strong>{formatRs(Math.max(0, member.expectedContribution - paid))}</strong></div></div><div className="progress"><span style={{ width: `${Math.min(100, (paid / member.expectedContribution) * 100)}%` }} /></div></article> })}</section></div>;
}

function Reports({ data, people, members, totalIncome, totalExpenses, balance, categoriesTotal, exportCsv, exportPdf }: { data: AppData; people: Record<string, string>; members: Record<string, AppData["members"][number]>; totalIncome: number; totalExpenses: number; balance: number; categoriesTotal: { category: ExpenseCategory; amount: number }[]; exportCsv: () => void; exportPdf: (mode: "complete" | "members" | "income" | "expenses") => void }) {
  const peopleRows = data.people.map((person) => ({ person, received: data.incomes.filter((i) => i.receivedByPersonId === person.id).reduce((s, i) => s + i.amount, 0), paid: data.expenses.filter((e) => e.paidByPersonId === person.id).reduce((s, e) => s + e.amount, 0) })).filter((item) => item.received || item.paid);
  return <div className="content"><div className="page-intro"><div><p className="eyebrow">Financial intelligence</p><h2>Reports</h2><p>Accountability views powered by every saved transaction.</p></div><div className="export-actions"><button className="secondary-button" onClick={exportCsv}><Download size={18} /> CSV</button><button className="primary-button" onClick={() => exportPdf("complete")}><FileText size={18} /> Complete PDF</button></div></div><div className="pdf-toolbar"><span>Download detailed reports</span><button onClick={() => exportPdf("members")}>Members PDF</button><button onClick={() => exportPdf("income")}>Income PDF</button><button onClick={() => exportPdf("expenses")}>Expenses PDF</button></div><div className="report-hero"><div><p className="eyebrow light">Final position</p><h2>{formatRs(balance)}</h2><p>Remaining balance · {data.tour.name}</p></div><div className="report-kpis"><span>Collected <strong>{formatRs(totalIncome)}</strong></span><span>Spent <strong>{formatRs(totalExpenses)}</strong></span></div></div><div className="reports-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Breakdown</p><h3>By category</h3></div></div>{categoriesTotal.map((item) => <div className="category-row" key={item.category}><span>{item.category}</span><strong>{formatRs(item.amount)}</strong></div>)}</section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Custody report</p><h3>Money handled</h3></div></div>{peopleRows.map((row) => <div className="person-row" key={row.person.id}><div className="avatar">{row.person.name[0]}</div><div><strong>{row.person.name}</strong><span>Net handled {formatRs(row.received - row.paid)}</span></div><div><small>Received</small><strong>{formatRs(row.received)}</strong></div><div><small>Paid</small><strong>{formatRs(row.paid)}</strong></div></div>)}</section></div><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Income vs expense</p><h3>Tour performance</h3></div></div><div className="comparison"><div><span>Income</span><strong className="positive-text">{formatRs(totalIncome)}</strong><div className="comparison-track"><span className="income-bar" style={{ width: "100%" }} /></div></div><div><span>Expenses</span><strong>{formatRs(totalExpenses)}</strong><div className="comparison-track"><span className="expense-bar" style={{ width: `${totalIncome ? Math.min(100, totalExpenses / totalIncome * 100) : 0}%` }} /></div></div></div></section></div>;
}

function FormField({ label, children }: { label: string; children: React.ReactNode }) { return <label className="form-field"><span>{label}</span>{children}</label>; }
function IncomeForm({ data, people, members, onClose, onSaved }: { data: AppData; people: Record<string, string>; members: Record<string, AppData["members"][number]>; onClose: () => void; onSaved: (data: AppData) => void }) {
  const [memberId, setMemberId] = useState(data.members[0]?.id ?? ""); const [amount, setAmount] = useState(""); const [method, setMethod] = useState<PaymentMethod>("Cash"); const [receivedBy, setReceivedBy] = useState(data.people[0]?.id ?? ""); const [saving, setSaving] = useState(false);
  const save = () => { const numeric = Number(amount); if (!memberId || !numeric || numeric < 0) return; setSaving(true); window.setTimeout(() => { onSaved(addIncome(data, { memberId, amount: numeric, paymentMethod: method, receivedByPersonId: receivedBy, date: "2026-09-17", time: new Date().toTimeString().slice(0, 5) })); }, 250); };
  return <Modal title="Add income" onClose={onClose}><div className="form-grid"><FormField label="Member"><select value={memberId} onChange={(e) => setMemberId(e.target.value)}>{Object.values(members).map((m) => <option key={m.id} value={m.id}>{people[m.personId]}</option>)}</select></FormField><FormField label="Amount"><input autoFocus type="number" inputMode="decimal" placeholder="Rs. 5,000" value={amount} onChange={(e) => setAmount(e.target.value)} /></FormField><FormField label="Payment method"><select value={method} onChange={(e) => setMethod(e.target.value as PaymentMethod)}>{methods.map((m) => <option key={m}>{m}</option>)}</select></FormField><FormField label="Received by"><select value={receivedBy} onChange={(e) => setReceivedBy(e.target.value)}>{data.people.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></FormField></div><button className="save-button" disabled={saving} onClick={save}>{saving ? "Saving..." : <><Check size={18} /> Save income</>}</button></Modal>;
}

function ExpenseForm({ data, people, onClose, onSaved }: { data: AppData; people: Record<string, string>; onClose: () => void; onSaved: (data: AppData) => void }) {
  const [category, setCategory] = useState<ExpenseCategory>("Fuel"); const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [paidBy, setPaidBy] = useState(data.people[0]?.id ?? ""); const [method, setMethod] = useState<PaymentMethod>("Cash"); const [location, setLocation] = useState(""); const [saving, setSaving] = useState(false);
  const save = () => { const numeric = Number(amount); if (!description || !numeric || numeric < 0) return; setSaving(true); window.setTimeout(() => onSaved(addExpense(data, { category, amount: numeric, description, paidByPersonId: paidBy, paymentMethod: method, location, date: "2026-09-17", time: new Date().toTimeString().slice(0, 5) })), 250); };
  return <Modal title="Add expense" onClose={onClose}><div className="form-grid"><FormField label="Category"><select value={category} onChange={(e) => setCategory(e.target.value as ExpenseCategory)}>{categories.map((c) => <option key={c}>{c}</option>)}</select></FormField><FormField label="Amount"><input autoFocus type="number" inputMode="decimal" placeholder="Rs. 4,500" value={amount} onChange={(e) => setAmount(e.target.value)} /></FormField><FormField label="What was it for?"><input placeholder="Vehicle fuel" value={description} onChange={(e) => setDescription(e.target.value)} /></FormField><FormField label="Paid by"><select value={paidBy} onChange={(e) => setPaidBy(e.target.value)}>{Object.entries(people).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></FormField><FormField label="Payment method"><select value={method} onChange={(e) => setMethod(e.target.value as PaymentMethod)}>{methods.map((m) => <option key={m}>{m}</option>)}</select></FormField><FormField label="Location"><input placeholder="Timergara" value={location} onChange={(e) => setLocation(e.target.value)} /></FormField></div><button className="save-button" disabled={saving} onClick={save}>{saving ? "Saving..." : <><Check size={18} /> Save expense</>}</button></Modal>;
}

function MemberForm({ data, onClose, onSaved }: { data: AppData; onClose: () => void; onSaved: (data: AppData) => void }) {
  const [name, setName] = useState(""); const [expected, setExpected] = useState(""); const [saving, setSaving] = useState(false);
  const save = () => { const numeric = Number(expected); if (!name || !numeric) return; setSaving(true); const next = addPerson(data, { name }); const person = next.people.at(-1)!; onSaved(addMember(next, { personId: person.id, expectedContribution: numeric })); };
  return <Modal title="Add member" onClose={onClose}><div className="form-grid"><FormField label="Full name"><input autoFocus placeholder="Ahmed" value={name} onChange={(e) => setName(e.target.value)} /></FormField><FormField label="Expected contribution"><input type="number" inputMode="decimal" placeholder="Rs. 7,000" value={expected} onChange={(e) => setExpected(e.target.value)} /></FormField></div><button className="save-button" disabled={saving} onClick={save}><Check size={18} /> Save member</button></Modal>;
}
